
####### MUDAR


swagger: "2.0"

schemes:
  - https 

host: localhost:8080
basePath: /bytebank-api/v1

info:
  version: "9.0.0"
  title: ByteBank Api
  description: Adminstra a movimentação bancária do correntista ByteBank e controla o acesso através de CPF e senha.
  contact:
    name: Support
    email: support@bytebank.com

consumes: 
  - application/json

produces: 
  - application/json

securityDefinitions:
  BasicAuth:
    type: basic

security: 
  - BasicAuth: []

paths:
  
  '/cliente':
    post:
      tags: 
        - Cliente   
      summary: Cadastra Cliente
      description: Cadastra um novo cliente.
      operationId: cadastraCliente
      parameters: 
      - in: body
        name: cliente_
        schema:
          $ref: '#/definitions/Cliente'
        required: true  
      responses:
        '201':
          description: Cadastro efetuado com sucesso!
          schema:
            $ref: '#/definitions/Cliente'
        '400':  
          description: Requisição inválida.
        '500':
          description: Erro no servidor
            
  '/conta/{agencia}/{conta}/{digito}/saldo':
    get:
      tags: 
        - Conta
      summary: Consulta Saldo Conta
      description: Consulta o saldo da conta do cliente utilizando agencia e conta.
      operationId: consultaSaldo
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: agencia
          required: true
          type: integer
          format: int32
          minLength: 4
          maxLength: 4
        - in: path
          name: conta
          required: true
          type: integer
          format: int64
          minLength: 4
          maxLength: 6
        - in: path
          name: digito
          required: true
          type: integer
          format: int32
          minLength: 1
          maxLength: 1
      responses:
        '200':
          description: Consulta a saldo efetuada com sucesso!
          schema:
            type: number
            format: double
        '400':  
          description: Requisição inválida.
        '401':  
          description: Requisição não autorizada.
        '404':  
          description: Registro não encontrado.
        '500':
          description: Erro no servidor
  
  '/extrato/{agencia}/{conta}/{digito}':
    get:
      tags: 
        - Extrato
      summary: Consulta Extrato Conta
      description: Consulta o extrato da conta do cliente utilizando agencia e conta.
      operationId: consultaExtrato
      security:
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: agencia
          required: true
          type: integer
          format: int32
          minLength: 4
          maxLength: 4
        - in: path
          name: conta
          required: true
          type: integer
          format: int64
          minLength: 4
          maxLength: 6
        - in: path
          name: digito
          required: true
          type: integer
          format: int32
          minLength: 1
          maxLength: 1
      responses:
        '200':
          description: Consulta a extrato efetuada com sucesso!
          schema:
            $ref: '#/definitions/Extrato'
        '400':  
          description: Requisição inválida.
        '401':  
          description: Requisição não autorizada.
        '404':  
          description: Registro não encontrado.
        '500':
          description: Erro no servidor

  
  '/transacao':
    post:
      tags: 
        - Transacao
      summary: Transacao em Conta 
      description: Efetua uma transacao de saque ou deposito em conta.
      operationId: novaTransacao
      security: 
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: body
          name: transacao
          schema:
            $ref: '#/definitions/Transacao'
          required: true
        - in: query
          name: tipo
          type: string
          enum:
          - saque
          - deposito
          required: true
      responses:
        '201':
          description: Transação efeturada com sucesso!
          schema:
            $ref: '#/definitions/Transacao'
        '400':  
          description: Requisição inválida.
        '401':  
          description: Requisição não autorizada.
        '500':
          description: Erro no servidor.
  
  
  '/transacao/{codigo}':
    put:
      tags: 
        - Transacao
      summary: Atualiza a transação
      description: Atualiza o valor da transação existente.
      operationId: atualizaValorTransacao
      security: 
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: codigo
          type: integer
          format: int64
          required: true
        - in: query
          name: valor
          type: number
          format: double  
          required: true
      responses:
        '204':
          description: Atualização efeturada com sucesso!
        '400':  
          description: Requisição inválida.
        '401':  
          description: Requisição não autorizada.
        '404':  
          description: Registro não encontrado.  
        '500':
          description: Erro no servidor.
    
    delete:
      tags: 
        - Transacao
      summary: Estorna a transação
      description: Estorna a transação efetuada.
      operationId: estornaTransacao
      security: 
        - BasicAuth: []
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: codigo
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: Estorno efeturado com sucesso!
        '400':  
          description: Requisição inválida.
        '401':  
          description: Requisição não autorizada.
        '404':  
          description: Registro não encontrado.  
        '500':
          description: Erro no servidor
            
tags: 
  - name: Cliente
  - name: Conta
  - name: Extrato
  - name: Transacao
            
definitions:
  
  Cliente:
    type: object
    properties:
      id:
        type: integer
        format: int64
      titular:
        type: string
      cpf:
        type: string
      password:
        type: string
        format: password
      contas:
        type: array
        items:
          $ref: '#/definitions/Conta'
    required: 
    - titular
    - cpf
    - password
  
  Conta:
    type: object
    properties:
      agencia:
        type: integer
        format: int32
      numero:
        type: integer
        format: int64
      digito:
        type: integer
        format: int32
      saldo:
        type: number
        format: double
      cliente:
        $ref: '#/definitions/Cliente'
      transacoes:
        type: array
        items:
          $ref: '#/definitions/Transacao'
  
  Transacao:
    type: object
    properties:
      id:
        type: integer
        format: int64
      tipo:
        type: string
        enum:
          - saque
          - deposito
      valor:
        type: number
        format: double
      data:
        type: string
        format: date-time
      conta:
        $ref: '#/definitions/Conta'
        
  Extrato:
    type: object
    properties:
      transacoes:
        type: array
        items:
          $ref: '#/definitions/Transacao'
