swagger: '2.0'

schemes: 
  - http
  - https
  
host: localhost:8085
basePath: /bytebank-api/v1

info:
  version: 1.0.0
  title: ByteBank Api
  description: Administra a movimentação bancária do correntista e controla o acesso através de CPF e password.
  contact:
    name: support
    email: support@bytebankapi.com
    
paths:
  '/cliente':
    post:
      summary: Cadastra Cliente
      description: Cadastro de novo cliente
      operationId: cadastraCliente
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters: 
        - in: body
          name: cliente_
          schema:
            type: object
            properties:
              titular:
                type: string
                example: Janete Santos
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            type: object
            properties:
              titular:
                type: string
                example: Janete Santos
        400:
          description: Requisição inválida
        500:
          description: Erro no servidor
    
  
