swagger: '2.0'

schemes: 
  - http
  - https
  
host: localhost:8085
basePath: /bytebank-api/v1

info:
  version: 1.0.0
  title: ByteBank Api
  description: Administra a movimentação bancária do correntista e controla o acesso através de CPF e senha.
  termsOfService: http://localhost:8085/bytebank-api/termos-uso
  contact:
    name: Suporte
    url: http://localhost:8085/bytebank-api/suporte
    email: suporte@bytebankapi.com
  license:
    name: Lincença
    url: http://localhost:8085/bytebank-api/licenca

paths:
  '/cliente':
    post:
      summary: Cadastra Cliente
      description: Cadastro de novo cliente
      operationId: cadastraCliente
      consumes: 
        - application/json
      produces: 
        - application/json
      parameters: 
        - in: body
          name: cliente_
          schema:
            type: object
            properties:
              titular:
                type: string
                example: Janete Santos
      responses:
        201:
          description: Cadastro efetuado com sucesso
          schema:
            type: object
            properties:
              titular:
                type: string
                example: Janete Santos
        400:
          description: Requisição inválida
        500:
          description: Erro no servidor

definitions:
  Cliente:
    type: object
    properties:
      id:
        type: integer
        format: int64
        example: 234
      titular:
        type: string
        example: Janete Santos
      cpf:
        type: string
        minLength: 11
        maxLength: 11
        example: 01234567890
      senha:
        type: string
        format: password
        example: senha123
      contas:
        type: array
        items:
          $ref: '#/definitions/Conta'

  Conta:
    type: object
    properties:
      agencia:
        type: integer
        format: int32
        example: 65
      numero:
        type: integer
        format: int64
        example: 4454
      digito:
        type: integer
        format: int32
        example: 1
      saldo:
        type: number
        format: double
        example: 100.34
      cliente:
        $ref: '#/definitions/Cliente'
      transacoes:
        {}
